# Enable GPIO driver support, used by the blinky sample
CONFIG_GPIO=y

# Enable IEC 60730 Class B safety library
CONFIG_IEC60730B=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_SHOW_TIMESTAMP=n
CONFIG_LOG_BACKEND_SHOW_LEVEL=n

# You can enable test debug logs
#CONFIG_IEC60730B_TEST_CLOCK_LOG_LEVEL=4
#CONFIG_IEC60730B_TEST_WDOG_LOG_LEVEL=4
#CONFIG_WDT_LOG_LEVEL_DBG=y

# Enable thread monitoring for debugger RTOS view support
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_INIT_STACKS=y
CONFIG_DEBUG_THREAD_INFO=y

# You can disable Watchdog and Clock test to prevent fail during debugging
#CONFIG_APP_SAFETY_TASK_WATCHDOG=n
#CONFIG_IEC60730B_TEST_CLOCK=n
#CONFIG_IEC60730B_TEST_WDOG=n

# You can use Zephyr HAL
#CONFIG_IEC60730B_HAL_ZEPHYR=y
